<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Add contact</title>
</head>
<body>
<a class="link-logout" href="../../index.php?path=logout">Logout</a>
<?php if ($_GET['action'] == 'add') : ?>
<form action="../../index.php?path=addContact" method="post">
<?php elseif ($_GET['action'] == 'edit') : ?>
<form action="../../index.php?path=editContact" method="post">
    <input type="hidden" name="contact_id" value="<?= $_GET['contact_id'] ?>">
<?php endif; ?>
    <?= $_GET['message']; ?>
    <table>
        <?php foreach($fields as $key => $value) : ?>
            <tr>
                <td><?= $value['name']; ?></td>
                <td> <input type="<?= $value['type']?>" name="<?= $key?>" value="<?= $value['value']?>"></td>
            </tr>
        <?php endforeach;?>
        <tr>
            <td></td>
            <?php if ($_GET['action'] == 'add') : ?>
            <td> <input class="button" type="submit" value="Create"></td>
            <?php elseif ($_GET['action'] == 'edit') : ?>
            <td> <input class="button" type="submit" value="Save"></td>
            <?php endif; ?>
            <td> <a class="link" href="../../index.php?path=viewContacts&list_id=<?= $_GET['id'];?>">Cancel</a> </td>
        </tr>
    </table>
</form>
</body>
</html>