<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Contacts</title>
</head>
<nav class="button-panel">
    <a class="link-back" href="../../index.php?controller=ListsController&action=show">Back</a>
    <a class="link-add" href="../../index.php?controller=ContactController&action=show&view=add&id=<?= $_GET['list_id'] ?>">Add</a>
    <a class="link-logout" href="../../index.php?controller=LogoutController&action=logout">Logout</a>
</nav>
<body>

    <table>
        <thead>
           <?php foreach ($fields as $key => $value) : ?>
              <?php if (!empty($value['name'])) : ?>
                 <td><?= $value['name']?></td>
              <?php endif; ?>
           <?php endforeach; ?>
           <td>Action</td>
        </thead>
        <?php foreach ($contacts as $key => $contact) : ?>
           <?php if ($contact['status'] == '1') : ?>
              <tr>
                 <?php foreach ($fields as $key => $value) : ?>
                    <?php if (!empty($value['name'])) : ?>
                      <td> <?= $contact[$key];?></td>
                    <?php endif; ?>
                 <?php endforeach; ?>
                 <td>
                    <a class="link" href="../../index.php?controller=ContactController&action=show&view=edit&contact_id=<?= $contact['id']?>&id=<?= $_GET['list_id']?>">Edit</a>
                    <a class="link" href="../../index.php?controller=ContactController&action=delete&id=<?= $contact['id']?>&list_id=<?= $_GET['list_id']   ;?>">Delete</a>
                 </td>
              </tr>
           <?php endif; ?>
        <?php endforeach; ?>
    </table>
</body>
</html>