<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lists</title>
    <link rel="stylesheet" href="/css/main.css">
</head>
<header>
    <h2>Contact Manager</h2>
    <div class="menu">
        <a class="link-logout" href="../../index.php?controller=LogoutController&action=logout">Logout</a>
    </div>
</header>
<body>
<h2>Create new list</h2>
<div class="message"><?= $_GET['message']?></div>
<form action="../../index.php?controller=ListController&action=add" method="post">
    <table>
        <tr>
            <td>
                <h4>List name</h4>
            </td>
        </tr>
        <tr>
            <td>
                <input type="text" name="listName" >
            </td>
            <td>
                <input class="button" name="submit" type="submit" value="Create">
            </td>
        </tr>
    </table>
</form>
<table class="lists-table">
    <thead>
        <td>List name</td>
        <td>Action</td>
    </thead>
    <?php foreach ($lists as $key => $list) :?>
        <?php if ($list['status'] == '1') :?>
        <tr>
            <td>
                <a href="../../index.php?controller=ContactsController&action=show&list_id=<?= $list['id'] ?>"><?= $list['list_name']; ?></a>
            </td>
            <td>
                <a class="link" href="../../index.php?controller=ListController&action=show&id=<?= $list['id'] ?>">Edit</a>
                <a class="link" href="../../index.php?controller=ListController&action=delete&id=<?= $list['id'] ?>">Delete</a>
            </td>
        </tr>
        <?php endif; ?>
     <?php endforeach; ?>
</<table>