<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <title>Login</title>
    <link rel="stylesheet" href="/css/main.css">
</head>
<header>
    <h2>Contact Manager</h2>
    <div class="menu">
        <a class="link-registration" href="../../index.php?controller=RegistrationController&action=show">Registration</a>
    </div>
</header>
<body>
    <form class="inform" action="../../index.php?controller=LoginController&action=login" method="post">
        <h3>Login</h3>
        <div class="message"><?= $_GET['message']; ?></div>
        <table class="form-table">
            <tr>
                <td>Login</td>
                <td> <input type="text" name="email" value="<?= $request['email']; ?>"> </td>
            </tr>
            <tr>
                <td>Password</td>
                <td> <input type="password" name="password" value="<?= $request['password']; ?>"> </td>
            </tr>
            <tr>
                <td></td>
                <td> <input class="button" type="submit" name="logbutton" value="Sing In"> </td>
            </tr>
        </table>
    </form>
</body>
</html>

