<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Registration</title>
      <link rel="stylesheet" href="/css/main.css">
  </head>
  <header>
      <h2>Contact Manager</h2>
      <div class="menu">
          <a class="link-back" href="../../index.php">Back</a>
      </div>
  </header>
  <body>

    <form class="inform" action="../../index.php?controller=RegistrationController&action=registrate    " method="post">
        <h1>Registration</h1>
        <div class="message"><?php echo !empty($_GET['message'])? $_GET['message'] : ""  ?></div>
          <table class="form-table">
            <tr>
              <td>First Name</td>
              <td> <input type="text" name="first_name" value="<?= $request['first']; ?>"> </td>
            </tr>
            <tr>
              <td>Last Name</td>
              <td> <input type="text" name="last_name" value="<?= $request['last']; ?>"> </td>
            </tr>
            <tr>
              <td>E-mail</td>
              <td> <input type="text" name="email" value="<?= $request['email']; ?>"> </td>
            </tr>
            <tr>
              <td>Password</td>
              <td> <input type="password" name="password"> </td>
            </tr>
            <tr>
              <td>Confirm Password</td>
              <td> <input type="password" name="cpassword"> </td>
            </tr>
            <tr>
              <td></td>
              <td> <input class="button" type="submit" name="createUser" value="Create"> </td>
            </tr>
      </table>
    </form>
  </body>
</html>
