<?php

require_once ROOT_PATH . '/Library/Contact.php';
require_once ROOT_PATH . '/Library/Session.php';

$contact = new Contact();
$fields = $contact->getFields();
$user = Session::getInstance()->get('CONTACT_USER');
$id = $_GET['contact_id'];

if (!empty($id)) {
    $result = $contact->getContact ($id);
    foreach ($fields as $key => $value) {
        $fields[$key]['value'] = $result[$key];
    }
} else {
  $fields['user_id']['value'] = $user['id'];
  $fields['list_id']['value'] = $_GET['id'];
  $result = Session::getInstance()->get('fields');
  foreach ($fields as $key => $value) {
      if (!empty($result)){
        $fields[$key]['value'] = $result[$key];
      }
  }
}?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Add contact</title>
</head>
<body>
<a class="button" href="../index.php?path=logout">Logout</a>
<?php if ($_GET['action'] == 'add') : ?>
<form action="../index.php?path=addContact" method="post">
<?php elseif ($_GET['action'] == 'edit') : ?>
<form action="../index.php?path=editContact" method="post">
    <input type="hidden" name="contact_id" value="<?= $id?>">
<?php endif; ?>
    <?= $_GET['message']; ?>
    <table>
        <?php foreach($fields as $key => $value) : ?>
            <tr>
                <td><?= $value['name']; ?></td>
                <td> <input type="<?= $value['type']?>" name="<?= $key?>" value="<?= $value['value']?>"></td>
            </tr>
        <?php endforeach;?>
        <tr>
            <td></td>
            <?php if ($_GET['action'] == 'add') : ?>
            <td> <input class="button" type="submit" value="Create"></td>
            <?php elseif ($_GET['action'] == 'edit') : ?>
            <td> <input class="button" type="submit" value="Save"></td>
            <?php endif; ?>
            <td> <a class="button" href="../index.php?path=viewContacts&list_id=<?= $_GET['id'];?>">Cancel</a> </td>
        </tr>
    </table>
</form>
</body>
</html>