<?php

require_once ROOT_PATH . '/Library/Session.php';
require_once ROOT_PATH . '/Library/Contact.php';

$session = Session::getInstance();
$cnt = new Contact();
$id = $_GET['list_id'];
$contacts = $cnt->getContacts($id);
$fields = $cnt->getFields();

if (empty($session->get('CONTACT_USER'))) {
    header('Location: index.php');
}
if (!empty($session->get('fields'))) {
  $session->clearValue('fields');
}
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Contacts</title>
</head>
<body>
    <a href="../index.php?path=viewLists">Back</a>
    <a href="../index.php?path=createForm&action=add&id=<?= $id ?>">Add</a>
    <a href="../index.php?path=logout">Logout</a>
    <table>
        <tr>
           <?php foreach ($fields as $key => $value) : ?>
              <?php if (!empty($value['name'])) : ?>
                 <td><?=$value['name']?></td>
              <?php endif; ?>
           <?php endforeach; ?>
           <td>Action</td>
        </tr>
        <?php foreach ($contacts as $key => $contact) : ?>
           <?php if ($contact['status'] == '1') : ?>
              <tr>
                 <?php foreach ($fields as $key => $value) : ?>
                    <?php if (!empty($value['name'])) : ?>
                      <td> <?= $contact[$key];?></td>
                    <?php endif; ?>
                 <?php endforeach; ?>
                 <td>
                    <a href="../index.php?path=createForm&action=edit&contact_id=<?= $contact['id']?>&id=<?= $id?>">Edit</a>
                    </br>
                    <a href="../index.php?path=deleteContact&id=<?= $contact['id']?>&list_id=<?= $id;?>">Delete</a>
                 </td>
              </tr>
           <?php endif; ?>
        <?php endforeach; ?>
    </table>
</body>
</html>