<?php

require_once 'lib/Contact.php';
require_once 'lib/Session.php';

$contact = new Contact();
$fields = $contact->getFields();
$user = Session::get('CONTACT_USER');
$id = $_GET['contact_id'];

if (!empty($id)) {
    $result = $contact->getContact ($id);
    foreach ($fields as $key => $value) {
        $fields[$key]['value'] = $result[0][$key];
    }
} else {
  $fields['user_id']['value'] = $user['id'];
  $fields['list_id']['value'] = $_GET['id'];
}?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Add contact</title>
</head>
<body>
<?php if ($_GET['action'] == 'add') : ?>
<form action="addContact.php?id=<?= $_GET['id']?>" method="post">
<?php elseif ($_GET['action'] == 'edit') : ?>
<form action="editContact.php?id=<?= $id?>" method="post">
<?php endif; ?>
    <table>
        <?php foreach($fields as $key => $value) : ?>
            <tr>
                <td><?= $value['name']; ?></td>
                <td> <input type="<?= $value['type']?>" name="<?= $key?>" value="<?= $value['value']?>"></td>
            </tr>
        <?php endforeach;?>
        <tr>
            <td></td>
            <?php if ($_GET['action'] == 'add') : ?>
            <td> <input type="submit" value="Create"></td>
            <?php elseif ($_GET['action'] == 'edit') : ?>
            <td> <input type="submit" value="Edit"></td>
            <?php endif; ?>
            <td> <a href="showContacts.php?id=<?= $_GET['id'];?>">Cancel</a> </td>
        </tr>
    </table>
</form>
</body>
</html>


