<?php error_reporting(E_ERROR);
ini_set('display_errors','On');?>
<?php   require_once 'lib/Contact.php';
        $contact= new Contact();
        $fields = $contact->getFields(); ?>

<?php $id = $_GET['contact_id'];?>
<?php if (!empty($id)) {
        require_once 'lib/Contact.php';
        $contact = new Contact();
        $result = $contact->getContact ($id);
        foreach ($fields as $key => $value) {
            $fields[$key]['value'] = $result[0][$key];
        }
      }?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Add contact</title>
</head>
<body>
<?php if ($_GET['action'] == 'add') : ?>
<form action="addContact.php" method="post">
<?php elseif ($_GET['action'] == 'edit') : ?>
<form action="editContact.php?id=   <?= $id?>" method="post">
<?php endif; ?>
    <table>
        <?php foreach($fields as $key => $value) : ?>
            <tr>
                <td><?= $value['name']; ?></td>
                <td> <input type="<?= $value['type']?>" name="<?= $key?>" value="<?= $value['value']?>"></td>
            </tr>
        <?php endforeach;?>
        <tr>
            <td></td>
            <?php if ($_GET['action'] == 'add') : ?>
            <td> <input type="submit" value="Create"></td>
            <?php elseif ($_GET['action'] == 'edit') : ?>
            <td> <input type="submit" value="Edit"></td>
            <?php endif; ?>
            <td> <a href="index.php">Cancel</a> </td>
        </tr>
    </table>
</form>
</body>
</html>


