<?php

require_once 'lib/Session.php';
require_once 'lib/ListContacts.php';

$userData = Session::get('CONTACT_USER');
$ls = new ListContacts();

if(empty(Session::get('CONTACT_USER'))) {
  header('Location: index.php');
}

$lists = $ls->getLists($userData['id']);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lists</title>
</head>
<body>
<a href="logout.php">Logout</a>
<h2>Create new list</h2>
<form action="addList.php" method="post">
    <table>
        <tr>
            <td>List name</td>
            <td> <input type="text" name="listName" > </td>
        </tr>
        <tr>
            <td></td>
            <td> <input name="submit" type="submit" value="Create"></td>
        </tr>
    </table>
</form>
<table>
    <tr>
        <td>List name</td>
        <td>Action</td>
    </tr>
    <?php foreach ($lists as $key => $list) :?>
        <?php if ($list['status'] == '1') :?>
        <tr>
            <td>
                <a href="showContacts.php?id=<?= $list['id'] ?>"><?= $list['list_name']; ?></a>
            </td>
            <td>
                <a href="showList.php?id=<?= $list['id'] ?>">Edit</a>
                </br>
                <a href="deleteList.php?id=<?= $list['id'] ?>">Delete</a>
            </td>
        </tr>
        <?php endif; ?>
     <?php endforeach; ?>
</<table>