<?php

require_once 'lib/Db.php';
require_once 'lib/Session.php';
require_once 'lib/ListContacts.php';

if (empty(Session::get('CONTACT_USER'))) {
    header('Location: index.php');
}
$list = new ListContacts();
$listName = $list->getList($_GET['id']);
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Edit list</title>
</head>
<body>
<a href="index.php">Back</a>
<a href="logout.php">Logout</a>
<form action="editList.php?id=<?= $_GET['id']?>" method="post">
    <p>Enter new list name.</p>
    <input type="text" name="newListName" value="<?= $listName;?>">
    <input type="submit" value="Save">
</form>
</body>
</html>