<?php
try {
    require_once 'lib/Session.php';
    require_once 'lib/Contact.php';

    $cnt = new Contact();

    $id = $_GET['id'];
    $contacts = $cnt->getContacts($id);
    $fields = $cnt->getFields();

    if (empty(Session::get('CONTACT_USER'))) {
      new Exception('User do not logged!');
    }
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Contacts</title>
    </head>
    <body>
        <a href="showContact.php?action=add&id=<?= $id ?>" type=>Add</a>
        <table>
            <tr>
                <?php foreach ($fields as $key => $value) : ?>
                    <?php if (!empty($value['name'])) : ?>
                        <td><?=$value['name']?></td>
                    <?php endif; ?>
                <?php endforeach; ?>
                <td>Action</td>
            </tr>
            <?php foreach ($contacts as $key => $contact) : ?>
                <?php if ($contact['status'] == '1') : ?>
                    <tr>
                        <?php foreach ($fields as $key => $value) : ?>
                            <?php if (!empty($value['name'])) : ?>
                                <td> <?= $contact[$key];?></td>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        <td>
                            <a href="showContact.php?action=edit&contact_id=<?= $contact['id']?>">Edit</a>
                            </br>
                            <a href="deleteContact.php?id=<?= $contact['id']?>">Delete</a>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    </body>
    </html>
<?php } catch(Exception $e) {
    header('Location: index.php');
}?>