<?php

require_once ROOT_PATH . '/Library/Session.php';
require_once ROOT_PATH . '/Library/ListContacts.php';

if (empty(Session::get('CONTACT_USER'))) {
    header('Location: index.php');
}
$list = new ListContacts();
$listName = $list->getList($_GET['id']);
?>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Edit list</title>
</head>
<body>
<a href="../index.php?path=viewLists">Back</a>
<a href="../index.php?path=logout">Logout</a>
<form action="../index.php?path=editList&id=<?= $_GET['id']?>" method="post">
    <p>Enter new list name.</p>
    <input type="text" name="newListName" value="<?= $listName;?>">
    <input type="submit" value="Save">
</form>
</body>
</html>