<?php
if(!empty($_GET['hash'])) {
    $data = (array)json_decode(base64_decode($_GET['hash']));
}
?>

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login</title>
  </head>
  <body>
  <a href="../index.php?path=registration">Registration</a>
    <h1>login</h1>
    <form class="inform" action="../index.php?path=autentificate" method="post">
      <table>
        <tr>
          <td>Login</td>
          <td> <input type="text" name="login" value="<?= $data['login']; ?>"> </td>
        </tr>
        <tr>
          <td>Password</td>
          <td> <input type="password" name="password" value="<?= $data['password']; ?>"> </td>
        </tr>
        <tr>
          <td></td>
          <td> <input type="submit" name="logbutton" value="Sing In"> </td>
        </tr>
      </table>
    </form>
  </body>
</html>
