<?php

require_once ROOT_PATH . '/Library/Session.php';

$data = json_decode(base64_decode($_GET['hash']), true);

?>

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Registration</title>
  </head>
  <body>
    <a href="../index.html">Back</a>
    <h1>Registration</h1>
    <?php echo !empty($_GET['message'])? $_GET['message'] : ""  ?>
    <form class="inform" action="../index.php?path=registrate" method="post">
      <table>
        <tr>
          <td>First Name</td>
          <td> <input type="text" name="firstName" value="<?= $data['first']; ?>"> </td>
        </tr>
        <tr>
          <td>Last Name</td>
          <td> <input type="text" name="lastName" value="<?= $data['last']; ?>"> </td>
        </tr>
        <tr>
          <td>E-mail</td>
          <td> <input type="text" name="login" value="<?= $data['login']; ?>"> </td>
        </tr>
        <tr>
          <td>Password</td>
          <td> <input type="password" name="password"> </td>
        </tr>
        <tr>
          <td>Confirm Password</td>
          <td> <input type="password" name="cpassword"> </td>
        </tr>
        <tr>
          <td></td>
          <td> <input type="submit" name="createUser" value="Create"> </td>
        </tr>
      </table>
    </form>
  </body>
</html>
