<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Registration</title>
  </head>
  <body>
    <a class="link-back" href="../../index.php">Back</a>
    <form class="inform" action="../../index.php?path=registration" method="post">
        <h1>Registration</h1>
        <?php echo !empty($_GET['message'])? $_GET['message'] : ""  ?>
          <table class="form-table">
            <tr>
              <td>First Name</td>
              <td> <input type="text" name="first_name" value="<?= $data['first']; ?>"> </td>
            </tr>
            <tr>
              <td>Last Name</td>
              <td> <input type="text" name="last_name" value="<?= $data['last']; ?>"> </td>
            </tr>
            <tr>
              <td>E-mail</td>
              <td> <input type="text" name="email" value="<?= $data['email']; ?>"> </td>
            </tr>
            <tr>
              <td>Password</td>
              <td> <input type="password" name="password"> </td>
            </tr>
            <tr>
              <td>Confirm Password</td>
              <td> <input type="password" name="cpassword"> </td>
            </tr>
            <tr>
              <td></td>
              <td> <input class="button" type="submit" name="createUser" value="Create"> </td>
            </tr>
      </table>
    </form>
  </body>
</html>
